VERSION 0.7
FROM node:latest
WORKDIR /ts-ms

deps:
    COPY package.json package-lock.json ./
    RUN pnpm install
    COPY tsconfig.json ./
    COPY src src

build:
    FROM +deps
    RUN pnpm run build
    SAVE ARTIFACT dist /dist AS LOCAL dist

docker:
    FROM +build
    EXPOSE 8080
    ENTRYPOINT ["node", "/ts-ms/dist/index.js"]
    SAVE IMAGE --push tamish13/cloak:ts

# test-setup:
#     FROM +deps
#     COPY jest.config.ts jest.config.integration.ts ./
#     COPY integration integration

# unit-test:
#     FROM +test-setup
#     RUN pnpm run test

all:
    BUILD +build
    BUILD +docker
